export const FETCHING_DATA = "FETCHING_DATA"
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS"
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE"
export const ADD_USER = "ADD_USER"
export const FETCHING_NOTEBOOKS = "FETCHING_NOTEBOOKS"
export const UPDATE_NOTEBOOKS = "UPDATE_NOTEBOOKS"


